# -*- coding: utf-8 -*-
"""entropy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOopQuTNqSw-5OsvMbb12r89wdFGt6DP
"""

import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from collections import Counter

#Entropy
import numpy as np

def entropy(y):
    hist = np.bincount(y)
    print(hist)
    ps = hist / len(y)
    return -np.sum([p * np.log2(p) for p in ps if p > 0])

y = np.array([2,2,0,0,1, 1, 1])
print(entropy(y))

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, *, value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value

    def is_leaf_node(self):
        return self.value is not None

class DecisionTree:
  def __init__(self,min_sample_split =2, max_depth=100,n_features=None):
    self.min_sample_split= min_sample_split
    self.max_depth= max_depth
    self.n_features = n_features
    self.root = None

def fit(self, X, y):
    self.n_features = X.shape[1] if self.n_features is None else min(self.n_features, X.shape[1])
    self.root = self._grow_tree(X, y)
DecisionTree.fit = fit

def predict(self, X):
    # Iterate over each sample (row) in X
    return np.array([self._traverse_tree(x, self.root) for x in X])
DecisionTree.predict = predict

"""1.stoppoing criteria
2.node becomes pure (only one class)
3.max depth reached  
3.too few sample left

# steps to grow a tree :
1. random select features
2. for each return try spliting at every unique value
3. select the best split using inforamtion gain
4. recursively grow left and right branches
"""

def _grow_tree(self, X, y, depth=0):
    n_samples, n_feats = X.shape
    n_labels = len(np.unique(y))

    if depth >= self.max_depth or n_labels == 1 or n_samples < self.min_sample_split:
        return Node(value=self._most_common_label(y))  # must return Node

    feat_idxs = np.random.choice(n_feats, self.n_features, replace=False)
    best_feat, best_thresh = self._best_criteria(X, y, feat_idxs)
    left_idxs, right_idxs = self._split(X[:, best_feat], best_thresh)

    # IMPORTANT: if split fails and both left/right are empty, return a leaf
    if len(left_idxs) == 0 or len(right_idxs) == 0:
        return Node(value=self._most_common_label(y))

    left = self._grow_tree(X[left_idxs, :], y[left_idxs], depth + 1)
    right = self._grow_tree(X[right_idxs, :], y[right_idxs], depth + 1)

    return Node(feature=best_feat, threshold=best_thresh, left=left, right=right)

DecisionTree._grow_tree = _grow_tree

def _best_criteria(self, X, y, feat_idxs):
        best_gain = -1
        split_idx = None
        split_thresh = None

        for feat_idx in feat_idxs:
            X_column = X[:, feat_idx]
            thresholds = np.unique(X_column)

            for threshold in thresholds:
                gain = self._information_gain(y, X_column, threshold)

                if gain > best_gain:
                    best_gain = gain
                    split_idx = feat_idx
                    split_thresh = threshold

        return split_idx, split_thresh
DecisionTree._best_criteria = _best_criteria

def _information_gain(self, y, X_column, split_thresh):
    parent_entropy = entropy(y)

    left_idxs, right_idxs = self._split(X_column, split_thresh)

    if len(left_idxs) == 0 or len(right_idxs) == 0:
        return 0

    n = len(y)
    n_l, n_r = len(left_idxs), len(right_idxs)

    e_l = entropy(y[left_idxs])
    e_r = entropy(y[right_idxs])

    child_entropy = (n_l / n) * e_l + (n_r / n) * e_r

    return parent_entropy - child_entropy


DecisionTree._information_gain = _information_gain

def _split(self, X_column, split_thresh):
    left_idxs = np.argwhere(X_column <= split_thresh).flatten()
    right_idxs = np.argwhere(X_column > split_thresh).flatten()
    return left_idxs, right_idxs


DecisionTree._split = _split

def _traverse_tree(self, x, node):
    if node.is_leaf_node():
        return node.value

    if x[node.feature] <= node.threshold:
        return self._traverse_tree(x, node.left)
    else:
        return self._traverse_tree(x, node.right)



DecisionTree._traverse_tree = _traverse_tree
DecisionTree._most_common_label = _most_common_label

def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)


data = datasets.load_breast_cancer()
X, y = data.data, data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1234
)

clf = DecisionTree(max_depth=10)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

acc = accuracy(y_test, y_pred)
print("Accuracy:", acc)